"""Added description field to MedicalRecord

Revision ID: 68a8d5aa4d19
Revises: edcb634d14ce
Create Date: 2025-01-29 17:21:52.098944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a8d5aa4d19'
down_revision = 'edcb634d14ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
